Vagrant.configure("2") do |config|
  config.vm.box = "envimation/ubuntu-xenial-docker"
  config.vm.define "course_demo" do |demo|
    demo.vm.network "public_network", ip: "192.168.100.101", :netmask => "255.255.255.0", :bridge => 'eth2'
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
end
