# -*- mode: ruby -*-
# vi: set ft=ruby :

KEY_PUB="../insecure-key.pub"
KEY_PRV="../insecure-key"

Vagrant.configure("2") do |config|
  config.vm.box = "envimation/ubuntu-xenial"
  config.vm.box_version = "1.0.3-1516241473"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  ssh_key_public  = File.readlines(KEY_PUB).first.strip
  config.vm.provision 'shell', inline: "echo #{ssh_key_public} >> /home/vagrant/.ssh/authorized_keys"
  config.vm.provision "file", source: KEY_PRV, destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision 'shell', inline: "chmod 400 /home/vagrant/.ssh/id_rsa"

  IP0 = 0
  (1..120).each do |i|
    config.vm.define "swarm#{i}" do |swarm|
      swarm.vm.network "public_network", ip: "192.168.137.#{i + IP0}", :netmask => "255.255.255.0", :bridge => 'eno1'
      swarm.vm.hostname = "swarm#{i}"
      swarm.vm.synced_folder "../data", "/vagrant_data",
        create: true, owner: "root", group: "root"
      swarm.vm.provision "shell", inline: <<-SHELL
        echo "This is swarm#{i}" > /etc/motd
      SHELL
    end
  end
end
